services:

  tf-img:
    container_name: tf-img
    build:
      dockerfile: ./docker/Dockerfile.tfjupyter
      context: ../
      args:
        TF_IMAGE: 2.11.0-jupyter
    #user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    volumes:
      - ../data:/tf/data
      - ../models:/tf/models
      - ../notebooks:/tf/notebooks
      - ../scripts:/tf/scripts
      - ../code:/home/code
      - ../.jupyter:/root/.jupyter
    ports:
      - 8890:8888
    command: ["/bin/sh"]
    # command: ["/usr/local/bin/jupyter",
    #   "notebook",
    #   "--ip", "0.0.0.0",
    #   "--port", "8888",
    #   "--no-browser",
    #   "--allow-root",
    #   "--NotebookApp.allow_origin_pat=https://.*vscode-cdn\\.net",
    #   "--notebook-dir", "/tf"]
